remote_theme: WildCodeSchool/workshops-jekyll-theme

# disable the jekyll-titles-from-headings plugin, 
# so first h1 will not be used as prior title of you page
titles_from_headings:
  enabled: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # possible values: default or tic-tac

style: dev # possible values: dev, data, ciber, design or wild.
title: 'Marmiwild I - MVC et PHP'
description: "Isoler la connexion BDD de l'affichage HTML"
# type: ''
main_image: 'images/food-1209503_1920.jpg' # http or relative path to image
show_clone: true
show_toc: true
lang: fr