CREATE DATABASE IF NOT EXISTS `WILD_DB_QUEST`;

CREATE TABLE IF NOT EXISTS `WILD_DB_QUEST`.`WIZARD` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `FIRSTNAME` VARCHAR(100) NOT NULL,
    `LASTNAME` VARCHAR(100) NOT NULL,
    `IS_MUGGLE` BOOLEAN NOT NULL,
    `BIRTHDAY`DATE NOT NULL,
    `BIRTH_PLACE` VARCHAR(255) NULL,
    `BIOGRAPHY` TEXT NULL,
    PRIMARY KEY (`ID`)
);

INSERT INTO `WIZARD`(
    ID,
    FIRSTNAME,
    LASTNAME,
    IS_MUGGLE,
    BIRTHDAY,
    BIRTH_PLACE,
    BIOGRAPHY
) VALUES (
    "",
    "Harry",
    "POTTER",
    TRUE,
    "1980-07-31",
    "LONDON",
    ""
);

CREATE TABLE IF NOT EXISTS `WILD_DB_QUEST`.`SCHOOL` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100) NOT NULL,
    `CAPACITY` INT NOT NULL,
    `COUNTRY` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`)
);

SHOW TABLES FROM WILD_DB_QUEST;